apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
{{- with .Values.global.vcdConfig }}
  vcloud-csi-config.yaml: |+
    vcd:
      host: {{ .site }}
      org: {{ .org }}
      vdc: {{ .ovdc }}
      vAppName: {{ .vAppName }}
    clusterid: {{ .clusterid | quote }}
immutable: {{ .immutable }}
{{- end }}
