{{- with .Values.storageClass }}
{{- if .enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  {{- if .delete.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  name: csi-vcd-sc-delete
provisioner: named-disk.csi.cloud-director.vmware.com
reclaimPolicy: Delete
parameters:
  storageProfile: {{ .delete.vcdStorageProfileName }}
  filesystem: {{ .delete.fileSystem }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  {{- if .retain.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  name: csi-vcd-sc-retain
provisioner: named-disk.csi.cloud-director.vmware.com
reclaimPolicy: Retain
parameters:
  storageProfile: {{ .retain.vcdStorageProfileName }}
  filesystem: {{ .retain.fileSystem }}
{{- end }}
{{- end }}
