{{- with .Values.storageClass }}
{{- if .enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .delete.isDefault | quote }}
  name: csi-vcd-sc-delete
provisioner: named-disk.csi.cloud-director.vmware.com
reclaimPolicy: Delete
parameters:
  storageProfile: {{ .delete.vcdStorageProfileName | quote }}
  filesystem: {{ .delete.fileSystem }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .retain.isDefault | quote }}
  name: csi-vcd-sc-retain
provisioner: named-disk.csi.cloud-director.vmware.com
reclaimPolicy: Retain
parameters:
  storageProfile: {{ .retain.vcdStorageProfileName | quote }}
  filesystem: {{ .retain.fileSystem }}
{{- end }}
{{- end }}
