ccmDeployment:
  replicas: 1
  revisionHistoryLimit: 2
  dnsPolicy: ClusterFirst
  imagePullPolicy: IfNotPresent
  image: projects.registry.vmware.com/vmware-cloud-director/cloud-provider-for-cloud-director
  tag: "1.2.0"
  tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: "Exists"