version: 2.1
orbs:
  architect: giantswarm/architect@4.38.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "push-to-default-app-catalog"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "cloud-provider-cloud-director"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
