global:
  basicAuthSecret:
    create: true
    username: ""
    password: ""
    refreshToken: ""

cloud-director-named-disk-csi-driver:
  basicAuthSecret:
    create: false
  csiConfigmap:
    site: "" # VCD endpoint with the format https://VCD_HOST. No trailing '/'
    org: "" # VCD organization name where the cluster should be deployed
    ovdc: "" # VCD virtual datacenter name where the cluster should be deployed
    vAppName: "" # "name" field of VCDCluster object in management cluster
    clusterid: "" # "Infra Id" field of VCDCluster object in management cluster

cloud-provider-for-cloud-director:
  basicAuthSecret:
    create: false
  cpiConfigmap:
    site: "" # VCD endpoint with the format https://VCD_HOST. No trailing '/'
    org: "" # VCD organization name where the cluster should be deployed
    ovdc: "" # VCD virtual datacenter name where the cluster should be deployed
    ovdcNetwork: "" # VCD virtual datacenter network to be used by the cluster
    vipSubnet: "" # Virtual IP CIDR for the external network
    vAppName: ""
    clusterid: "" # "Infra Id" in VCDCluster object in management cluster
