ccmDeployment:
  replicas: 1
  revisionHistoryLimit: 2
  dnsPolicy: Default
  imagePullPolicy: IfNotPresent
  image: projects.registry.vmware.com/vmware-cloud-director/cloud-provider-for-cloud-director
  tag: 1.1.1.latest
  tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: "Exists"
