cpiConfigmap:
  site: "" # VCD endpoint with the format https://VCD_HOST. No trailing '/'
  org: "" # VCD organization name where the cluster should be deployed
  ovdc: "" # VCD virtual datacenter name where the cluster should be deployed
  ovdcNetwork: "" # VCD virtual datacenter network to be used by the cluster
  vipSubnet: "" # Virtual IP CIDR for the external network
  clusterid: "" # "Infra Id" in VCDCluster object in management cluster
  vAppName: ""
  enableVirtualServiceSharedIP: false # supported for VCD >= 10.4 - not used yet
  oneArm:
    startIP: "192.168.8.2" # Will disappear in future versions
    endIP: "192.168.8.100" # Will disappear in future versions
  immutable: true

ccmDeployment:
  replicas: 1
  revisionHistoryLimit: 2
  dnsPolicy: Default
  imagePullPolicy: IfNotPresent
  image: projects.registry.vmware.com/vmware-cloud-director/cloud-provider-for-cloud-director
  tag: 1.1.1.latest
  tolerations:
    - key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
      effect: NoSchedule
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: "Exists"
