apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-ccm-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
{{- with .Values.global.vcdConfig }}
  vcloud-ccm-config.yaml: |+
    vcd:
      host: {{ .site }}
      org: {{ .org }}
      vdc: {{ .ovdc }}
    loadbalancer:
      network: {{ .ovdcNetwork }}
      vipSubnet: {{ .vipSubnet }}
      oneArm:
        startIP: {{ .oneArm.startIP }}
        endIP: {{ .oneArm.endIP }}
      ports:
        http: 80
        https: 443
      certAlias: {{ .clusterid }}-cert
    clusterid: {{ .clusterid }} 
    vAppName: {{ .vAppName }}
immutable: {{ .immutable }}
{{- end }}
