global:
  basicAuthSecret:
    create: true
    name: vcloud-basic-auth
    refreshToken: ""  # Required only when `create: true`

  vcdConfig:
    site: ""  # VCD endpoint with the format https://VCD_HOST. No trailing '/'
    org: ""  # VCD organization name where the cluster should be deployed
    ovdc: ""  # VCD virtual datacenter name where the cluster should be deployed
    ovdcNetwork: ""  # VCD virtual datacenter network to be used by the cluster
    vipSubnet: ""  # Virtual IP CIDR for the external network
    clusterid: ""  # "Infra Id" field of VCDCluster object in management cluster
    vAppName: ""
    enableVirtualServiceSharedIP: true  # Multiple VS can share an IP if true.
    oneArm:
      enabled: false  # Creates a NAT rule instead of direct LB IP if true.
      startIP: "192.168.8.2"
      endIP: "192.168.8.100"
    immutable: false  # Associated configmaps will use this flag

cloud-director-named-disk-csi-driver:
  controllerStatefulset:
    csiAttacher:
      image: quay.io/giantswarm/csi-attacher
    csiProvisioner:
      image: quay.io/giantswarm/csi-provisioner
    csiPlugin:
      image: quay.io/giantswarm/csi-cloud-director
      tag: 1.3.2.68f48f4

  nodeDaemonset:
    nodeDriverRegistrar:
      image: quay.io/giantswarm/csi-node-driver-registrar
    csiPlugin:
      image: quay.io/giantswarm/csi-cloud-director
      tag: 1.3.2.68f48f4

  storageClass:
    enabled: true
    delete:
      isDefault: true
      vcdStorageProfileName: ""  # Default SP used if empty.
      fileSystem: "ext4"
    retain:
      isDefault: false
      vcdStorageProfileName: ""  # Default SP used if empty.
      fileSystem: "ext4"

cloud-provider-for-cloud-director:
  ccmDeployment:
    image: quay.io/giantswarm/cpi-cloud-director
    tag: "1.2.0-de4b612"
