apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  vcloud-csi-config.yaml: |+
    vcd:
      host: {{ .Values.csiConfigmap.site }}
      org: {{ .Values.csiConfigmap.org }}
      vdc: {{ .Values.csiConfigmap.ovdc }}
      vAppName: {{ .Values.csiConfigmap.vAppName }}
    clusterid: {{ .Values.csiConfigmap.clusterid | quote }}
immutable: {{ .Values.csiConfigmap.immutable }}