kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-vcd-controllerplugin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  serviceName: csi-vcd-controller-service
  replicas: {{ .Values.controllerStatefulset.replicas }}
  selector:
    matchLabels:
      app: csi-vcd-controllerplugin
  template:
    metadata:
      labels:
        app: csi-vcd-controllerplugin
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccount: csi-vcd-controller-sa
      dnsPolicy: {{ .Values.controllerStatefulset.dnsPolicy }}
      containers:
        - name: csi-attacher
          image: {{ .Values.controllerStatefulset.csiAttacher.image }}:{{ .Values.controllerStatefulset.csiAttacher.tag }}
          imagePullPolicy: {{ .Values.controllerStatefulset.imagePullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --timeout=180s
            - --v=5
          env:
            - name: ADDRESS
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-provisioner
          image: {{ .Values.controllerStatefulset.csiProvisioner.image }}:{{ .Values.controllerStatefulset.csiProvisioner.tag }}
          imagePullPolicy: {{ .Values.controllerStatefulset.imagePullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --timeout=300s
            - --v=5
          env:
            - name: ADDRESS
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: vcd-csi-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.controllerStatefulset.csiPlugin.image }}:{{ .Values.controllerStatefulset.csiPlugin.tag }}
          imagePullPolicy: {{ .Values.controllerStatefulset.imagePullPolicy }}
          command:
            - /opt/vcloud/bin/cloud-director-named-disk-csi-driver
            - --cloud-config=/etc/kubernetes/vcloud/vcloud-csi-config.yaml
            - --endpoint=$(CSI_ENDPOINT)
            - --v=5
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: HostToContainer
            - name: pv-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi/pv
              mountPropagation: "Bidirectional"
            - name: vcloud-csi-config-volume
              mountPath: /etc/kubernetes/vcloud
            - name: vcloud-basic-auth-volume
              mountPath: /etc/kubernetes/vcloud/basic-auth
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: pv-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi/pv
            type: DirectoryOrCreate
        - name: vcloud-csi-config-volume
          configMap:
            name: vcloud-csi-configmap
        - name: vcloud-basic-auth-volume
          secret:
            secretName: vcloud-basic-auth