apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-ccm-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  vcloud-ccm-config.yaml: |+
    vcd:
      host: {{ .Values.configmap.site }}
      org: {{ .Values.configmap.org }}
      vdc: {{ .Values.configmap.ovdc }}
    loadbalancer:
      oneArm:
        startIP: {{ .Values.configmap.oneArm.startIP }}
        endIP: {{ .Values.configmap.oneArm.endIP }}
      ports:
        http: 80
        https: 443
      network: {{ .Values.configmap.ovdcNetwork }}
      vipSubnet: {{ .Values.configmap.vipSubnet }}
      certAlias: {{ .Values.configmap.clusterid }}-cert
      enableVirtualServiceSharedIP: {{ .Values.configmap.enableVirtualServiceSharedIP }}
    clusterid: {{ .Values.configmap.clusterid }}
    vAppName: {{ .Values.configmap.vAppName }}
immutable: true