apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-ccm-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  vcloud-ccm-config.yaml: |+
    vcd:
      host: {{ .Values.cpiConfigmap.site }}
      org: {{ .Values.cpiConfigmap.org }}
      vdc: {{ .Values.cpiConfigmap.ovdc }}
      vAppName: {{ .Values.cpiConfigmap.vAppName }}
      network: {{ .Values.cpiConfigmap.ovdcNetwork }}
      vipSubnet: {{ .Values.cpiConfigmap.vipSubnet }}
    loadbalancer:
      oneArm:
        startIP: {{ .Values.cpiConfigmap.oneArm.startIP }}
        endIP: {{ .Values.cpiConfigmap.oneArm.endIP }}
      ports:
        http: 80
        https: 443
      certAlias: {{ .Values.cpiConfigmap.clusterid }}-cert
    clusterid: {{ .Values.cpiConfigmap.clusterid | quote }} 
immutable: {{ .Values.cpiConfigmap.immutable }}