apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-ccm-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  vcloud-ccm-config.yaml: |+
    vcd:
      host: {{ .Values.cpiConfigmap.site }}
      org: {{ .Values.cpiConfigmap.org }}
      vdc: {{ .Values.cpiConfigmap.ovdc }}
    loadbalancer:
      oneArm:
        startIP: {{ .Values.cpiConfigmap.oneArm.startIP }}
        endIP: {{ .Values.cpiConfigmap.oneArm.endIP }}
      ports:
        http: 80
        https: 443
      network: {{ .Values.cpiConfigmap.ovdcNetwork }}
      vipSubnet: {{ .Values.cpiConfigmap.vipSubnet }}
      certAlias: {{ .Values.cpiConfigmap.clusterid }}-cert
      enableVirtualServiceSharedIP: {{ .Values.cpiConfigmap.enableVirtualServiceSharedIP }}
    clusterid: {{ .Values.cpiConfigmap.clusterid }}
    vAppName: {{ .Values.cpiConfigmap.vAppName }}
immutable: {{ .Values.cpiConfigmap.immutable }}