apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmware-cloud-director-ccm
    {{- include "labels.common" . | nindent 4 }}
  name: vmware-cloud-director-ccm
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: vmware-cloud-director-ccm
  template:
    metadata:
      labels:
        app: vmware-cloud-director-ccm
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: {{ .Values.deployment.dnsPolicy }}
      hostNetwork: true
      serviceAccountName: cloud-controller-manager
      containers:
        - name: vmware-cloud-director-ccm
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
            - /opt/vcloud/bin/cloud-provider-for-cloud-director
            - --cloud-provider=vmware-cloud-director
            - --cloud-config=/etc/kubernetes/vcloud/vcloud-ccm-config.yaml
            - --allow-untagged-cloud=true
          volumeMounts:
            - name: vcloud-ccm-config-volume
              mountPath: /etc/kubernetes/vcloud
            - name: vcloud-ccm-vcloud-basic-auth-volume
              mountPath: /etc/kubernetes/vcloud/basic-auth
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: "Exists"
      volumes:
        - name: vcloud-ccm-config-volume
          configMap:
            name: vcloud-ccm-configmap
        - name: vcloud-ccm-vcloud-basic-auth-volume
          secret:
            secretName: vcloud-basic-auth